version: "1.0.0"
services:
  worker-a:
    build: .
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro
  worker-b:
    build: .
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro
