version: "1.0.0"
services:
  generic-worker-a:
    build: .
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro
  generic-worker-b:
    build: .
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro
