version: "1.0.0"
services:
  worker-consumer-a:
    container_name: worker-a
    build: .
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro
  worker-consumer-b:
    container_name: worker-b
    build: .
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro
  publisher:
    build: 
      dockerfile: ./SimpleQueueService.Dockerfile
    volumes: 
      - $USERPROFILE\.aws\credentials:/root/.aws/credentials:ro

